version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build: .
    command: python manage.py runserver_plus 0.0.0.0:8000 --cert-file ./certs/0.0.0.0.pem --key-file ./certs/0.0.0.0-key.pem
    volumes:
      - ./foodles_second_coding_test_backend:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET=devsecret
      - FRONTEND_URL=https://127.0.0.1:3000
      - FRONTEND_DOMAIN=127.0.0.1
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - db
