# Generated by Django 4.0 on 2023-03-20 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_client_session_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
