# Generated by Django 4.0 on 2023-03-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
